### ISSUE TITLE
unit_of_measurement: °C

### ISSUE THREAD

**Issue by razzietheman** [popeen/Home-Assistant-Custom-Component-Temperatur-Nu#1]
denna visar inte °C i GUI , och kan inte lägga till  " unit_of_measurement: °C " i min sensors.yaml för att få den att visa detta heller , på min print står den som utomhustemp under balkong
![Screenshot_20230216_184449](https://user-images.githubusercontent.com/58360064/219446068-1532bdb2-0206-4c10-a5ae-5f36b3f4e6f6.jpg)

**Comment by popeen** [comment]
Good catch!
Det måste vi ju självklart ha med
