### ISSUE TITLE
I have trouble getting this to work and need help

### ISSUE THREAD

**Issue by HAPSagan** [popeen/Home-Assistant-Custom-Component-Temperatur-Nu#2]
Hi
I have trouble getting this to work and need help . Don't know if this is the right way but it's the only way I can think of right now.
I have split my configuration and have in:

configuration.yaml

sensor: !include_dir_merge_list sensor/
template: !include_dir_merge_list template/

In the config folder I have a folder called "sensor" and another called "template"
In these folders I have created filesfor different things.

Where and what should i write to get te sensor from "UNDERSÅKER/ROMO"?

If I want to report my own sensor (I have created a request for Järpen/Svensta)?

**Comment by HAPSagan** [comment]
Hi again
Problem partly solved.

The remaining part is how I report the one I created.

Peter

**Comment by popeen** [comment]
Hi,

Happy to hear it.
To report you create an automation that calls the send_temperature service, I recommend setting it to run every three minutes. 

My automation look like this. The hash value is the secret hash you received from Temperatur.nu for your station.
![image](https://github.com/popeen/Home-Assistant-Custom-Component-Temperatur-Nu/assets/5898388/0dd3c537-ceba-4c7d-9eff-5c47802ee70e)

> alias: Temperatur.nu rapportering (Service)
> description: ""
> trigger:
>   - platform: time_pattern
>     minutes: /3
> condition: []
> action:
>   - service: temperatur_nu.send_temperature
>     data:
>       sensor: sensor.outdoor_temperature
>       hash: 7815dummycbfdummy6894bdummyd330e
> mode: single

Hope that helps
